collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
remote_theme: pages-themes/hacker@v0.2.0
title: Amor Fati
description: This site is for sharing my ideas with the world.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 
  - jekyll-remote-theme

