collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/time-machine@v0.2.0
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
title: Arabica
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 
  - jekyll-remote-theme

